name: Build, Test & Migrate

on:
  push:
    branches: ['main', 'v2']
  pull_request:
    branches: ['main', 'v2']
  workflow_call:

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml

  migration-test:
    name: Mirgation Test
    needs: [build-and-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: ./.github/actions/setup-production-env
      - name: Start previous release
        run: docker compose -f deploy-compose.yml run backend npm run setup
      - name: Run Migration
        run: docker compose run backend npm run setup
